services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080 (for the local dev Nginx server block)
    container_name: carmodpicker_frontend