apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carmodpicker-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: carmodpicker-backend-svc # From backend-service.yaml
            port:
              number: 8000 # Port exposed by carmodpicker-backend-svc
      - path: /
        pathType: Prefix
        backend:
          service:
            name: carmodpicker-frontend-svc # From frontend-service.yaml
            port:
              number: 80 # Port exposed by carmodpicker-frontend-svc